---
title: Promise.catch
permalink: /Javascript/Promise/catch/
excerpt: "El método .catch() de Promise maneja los rechazos de una promesa en JavaScript."
date: 2024-01-29
last_modified_at: 2024-02-02
key: Javascript.P.Promise.catch
category: Javascript
tags: [metodo javascript,ecmascript 6]
image: "/assets/images/javascript.png"
sidebar:
  nav: javascript
---

## Descripción


El método `.catch()` del objeto [`Promise`](https://www.w3api.com/Javascript/Promise/) se utiliza para manejar los rechazos de una promesa. Si la promesa es rechazada, este método devuelve una nueva promesa que maneja el rechazo con la función proporcionada.


## Sintaxis


```javascript
p.catch(onRejected);
p.catch(function(reason) { // rejection });
```


## Parámetros

- **onRejected**: Esta es una función que se ejecutará si la Promesa es rechazada. La razón del rechazo se pasa a esta función.

## Ejemplo


```javascript
let promesa = new Promise((resolve, reject) => {
    let resultado = false; // supongamos una condición que resulta en un fallo

    if (resultado) {
        resolve("La promesa se resolvió exitosamente");
    } else {
        reject("La promesa fue rechazada");
    }
});

promesa
    .then(message => {
        console.log(message);
    })
    .catch(error => {
        console.log(error);
    });
```


En este ejemplo, creamos una nueva Promesa que se rechaza debido a la condición de fallo. Usamos el método `.catch()` para manejar el rechazo de la promesa y registrar el error en la consola.


## Artículos

- [Crear Promesa en Javascript](https://lineadecodigo.com/javascript/crear-promesa-en-javascript/)
- [Gestionar Promesas Rechazadas](http://lineadecodigo.com/html5/gestionar-promesas-rechazadas/)
